version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    environment:
      - GIT_SSL_NO_VERIFY=1
    build:
      context: .
      dockerfile: Dockerfile.dev
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: worker_tank_aAVIY@20SDnVV3
      POSTGRES_USER: worker_tank
    ports:
      - "5432:5432"
 
